name: release-artifacts

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build artifacts
        run: ./gradlew clean build

      - name: Upload assets to GitHub, Modrinth, and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ""
          game-version-filter: releases | min-major | min-minor
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
